name: Documentation

on:
    push:
        branches:
            - main
        tags: '*'
    pull_request:
        branches:
            - main
    # can add tags if needed
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: julia-actions/cache@v1
            - uses: julia-actions/julia-buildpkg@latest
            - run:  julia --project=docs -e 'using Pkg; Pkg.add([Pkg.PackageSpec(url = "https://github.com/asinghvi17/TSFrames.jl", rev = "join"), Pkg.PackageSpec(path = "./EventStudies.jl")])'
            - uses: julia-actions/julia-docdeploy@latest
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}

